version: "3.9"

services:
  api:
    build: ./almacenamiento
    container_name: api_waze
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=8080
      - HOST=localhost
    env_file:
      - .env

  scraper:
    build: ./scraper
    container_name: scraper_waze
    depends_on:
      - api
    environment:
      - URL_API=http://api:8080/eventos

  cache:
    build: ./cache
    container_name: cache_waze
    ports:
      - "4000:4000"
    depends_on:
      - api
    environment:
      - PORT=4000
      - CACHE_POLICY=LFU #LRU o LFU
      - CACHE_SIZE=3
      - API_BACKEND=http://api:8080
      - HOST=0.0.0.0

  trafico:
    build: ./trafico
    container_name: trafico_waze
    environment:
      - CACHE_URL=http://cache:4000
    depends_on:
      - cache

  filtrador:
    build: ./filtrador
    container_name: filtrador_waze
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=eventosdb
      - COLLECCION_ORIGEN=eventos
      - COLLECCION_DESTINO=eventos_filtrados
      - EXPORT_PATH=../procesador/filtrados.csv
    volumes:
      - ./filtrador:/app
      - ./procesador:/app/../procesador
    working_dir: /app

  procesador:
    build: ./procesador
    container_name: procesador_waze
    volumes:
      - ./procesador:/app
    working_dir: /app
    stdin_open: true
    tty: true
    depends_on:
      - filtrador

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elastic_waze
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - network.host=0.0.0.0
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana_waze
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata: